default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: sample_app

test:
  <<: *default
  database: sample_app

production:
  <<: *default
  database: sample_app
  username: root
  password:
